import { SpendBudget } from '../types/telemetry';
import { ProviderConfig } from '../types/routing';
import { ClientSyncResult } from '../types/config';

export class DiagnosticService {
  /**
   * Sanitizes any sensitive string, replacing API keys, tokens, and authorization headers with safe masked strings
   */
  public static sanitizeSensitiveData(input: string): string {
    if (!input) return '';
    return input
      // Redact OpenAI keys
      .replace(/sk-[a-zA-Z0-9_-]{20,}/g, 'sk-***REDACTED***')
      // Redact Anthropic keys
      .replace(/sk-ant-[a-zA-Z0-9_-]{20,}/g, 'sk-ant-***REDACTED***')
      // Redact GitHub tokens
      .replace(/ghp_[a-zA-Z0-9]{20,}/g, 'ghp_***REDACTED***')
      .replace(/github_pat_[a-zA-Z0-9_]{20,}/g, 'github_pat_***REDACTED***')
      // Redact AWS keys
      .replace(/AKIA[0-9A-Z]{16}/g, 'AKIA***REDACTED***')
      // Redact Bearer tokens
      .replace(/Bearer\s+[a-zA-Z0-9._~+/-]{10,}/gi, 'Bearer ***REDACTED***')
      // Redact URLs with passwords
      .replace(/(postgresql|postgres|mysql|redis|mongodb):\/\/([^:]+):([^@]+)@/gi, '$1://$2:***REDACTED***@')
      // Redact Slack tokens
      .replace(/xoxb-[0-9a-zA-Z-]+/g, 'xoxb-***REDACTED***')
      // Redact Notion secrets
      .replace(/secret_[a-zA-Z0-9]{20,}/g, 'secret_***REDACTED***');
  }

  /**
   * Generates a complete GitHub Markdown diagnostic issue report
   */
  public static generateSanitizedReport(context: {
    appVersion: string;
    os: string;
    proxyPort: number;
    proxyRunning: boolean;
    budget: SpendBudget;
    providers: ProviderConfig[];
    recentSyncResults: ClientSyncResult[];
    recentErrorLogs?: string[];
  }): string {
    const timestamp = new Date().toISOString();
    const providersTable = context.providers
      .map(p => `| ${p.name} | ${p.isEnabled ? '✅ Enabled' : '⚪ Disabled'} | ${p.isHealthy ? '🟢 Healthy' : '🔴 Unhealthy'} | ${p.lastPingMs ? p.lastPingMs + 'ms' : 'N/A'} |`)
      .join('\n');

    const syncTable = context.recentSyncResults.length > 0
      ? context.recentSyncResults
          .map(s => `| ${s.clientName} | ${s.isSuccess ? '✅ Success' : '❌ Failed'} | ${s.toolsInjected} tools | \`${DiagnosticService.sanitizeSensitiveData(s.filePath)}\` |`)
          .join('\n')
      : '_No client synchronization performed yet._';

    const errorsBlock = context.recentErrorLogs && context.recentErrorLogs.length > 0
      ? context.recentErrorLogs.map(e => DiagnosticService.sanitizeSensitiveData(e)).join('\n')
      : 'No critical errors recorded in current session.';

    return `### TetherIQ Diagnostic & Health Report
Generated: \`${timestamp}\`  
App Version: \`${context.appVersion}\`  
Platform: \`${context.os}\`  

#### 1. Proxy Gateway State
- **Status:** ${context.proxyRunning ? '🟢 Running on `127.0.0.1:' + context.proxyPort + '`' : '🔴 Stopped'}
- **Daily Spend:** $${context.budget.currentDailySpend.toFixed(3)} / $${context.budget.dailyLimit.toFixed(2)}
- **Circuit Breaker Tripped:** ${context.budget.isCircuitBreakerTripped ? '⚠️ YES (Hard cutoff active)' : '🟢 No (Operating normally)'}

#### 2. Provider Health Matrix
| Provider | Status | Health | Latency |
| :--- | :--- | :--- | :--- |
${providersTable}

#### 3. Client Config Synchronization
| Client Target | Status | Injected | Target Path |
| :--- | :--- | :--- | :--- |
${syncTable}

#### 4. Sanitized Logs & Error Traces
\`\`\`text
${errorsBlock}
\`\`\`

---
*Generated by TetherIQ 1-Click Diagnostics. All API keys and auth tokens have been stripped.*`;
  }
}
